### PR TITLE
Fix setFitToContent error in old Joplin.

### LINKED ISSUE #14: setFitToContent does not exist (Incompatible Joplin version)
```
Uncaught exception in plugin "joplin-plugin-conflict-resolution": Error: Property or method "setFitToContent" does not exist in "joplin.views.dialogs.setFitToContent"
```

Plugin has an app min version of `2.0.9`, but the command [setFitToContent](https://github.com/laurent22/joplin/commit/c89037b4a28be1a8f33ad963e8e3e0f73df37602) does not exist in any released or beta version yet!

### PR DESCRIPTION
**Pull request by Ahmad45123**
I've made a sort of failsafe where it simply reverts the CSS changes back to fixed px values in case setFitToContent doesn't exist. That way the plugin still works with old Joplin versions.

I could have just dropped support for older versions and waited a new Joplin release, but didn't wanna do that.

### CODE REVIEW

**Comment by Ahmad45123** [comment]
This fixes #14

File: api/JoplinViewsDialogs.d.ts [hunk 1]
```diff
@@ -59,4 +59,6 @@ export default class JoplinViewsDialogs {
      * Opens the dialog
      */
     open(handle: ViewHandle): Promise<DialogResult>;
+
+    setFitToContent(handle: ViewHandle, status: boolean) : Promise<boolean>;
```
Comment (Ahmad45123) [inline api/JoplinViewsDialogs.d.ts:63]: I added this here because when using `(as any)` caused weird issues :/

File: src/DiffWindow.ts [hunk 2]
```diff
@@ -50,7 +50,15 @@ export class DiffWindow {
...
             },
         ]);
-        await (this.joplinDialogs as any).setFitToContent(this.handle, false);
+
+        try {
+            await this.joplinDialogs.setFitToContent(this.handle, false);
+        } catch {
+            // If an exception occurs, that means setFitToContent failed, and we must add the CSS to support old versions.
+            // The below CSS files basically overrides the changes needed to make the CSS work without setFitToContent.
+            console.log('Concflict Resolution: Error setting fitToContent, injecting old styling instead.');
```
Comment (CalebJohn) [inline src/DiffWindow.ts:59]: Just a typo in the message Concflict->Conflict

**Review by CalebJohn — APPROVED** [review]

**Comment by CalebJohn** [comment]
@Ahmad45123 Sorry I took so long on this review. Yesterday was a busy one for me. The changes look good, there's just a typo in your log message, but I've pre-approved the PR so feel free to merge once the typo is fixed! Nice work!

**Comment by Ahmad45123** [comment]
> @Ahmad45123 Sorry I took so long on this review. Yesterday was a busy one for me. The changes look good, there's just a typo in your log message, but I've pre-approved the PR so feel free to merge once the typo is fixed! Nice work!

No worries :) Thank you for the review!
